### ISSUE TITLE
Windows are not unique, possibly causing bugs?

### ISSUE THREAD

**Issue by fishcu** [pnprog/goreviewpartner#14]
In most windows, when you click a button that opens another window, it will always generate a new window instance. For example, in the main window, you can click on "settings" multiple times, each opening a new window. I am not sure how robust the program is against multiple windows changing global variables. In any case, the user experience would be better if instead of creating a new window each time, the existing one would be brought into focus.

**Comment by pnprog** [comment]
Hi @fishcu !

In fact, there are not a lot of global variables shared between windows. But one set of data that are shared all over the software are the data from the **config.ini** file. At the beginning, I was trying to read them in one place, then share them everywhere, but now, I just open and read the **config.ini** file every time I need a data. On modern OS (well, at least on GNU/Linux) once a file as been read, it stays for a while in memory, so next time the program access it, it access it from memory, not from hard drive.

Regarding, the opening of multiple windows, there are cases that I think are useful, and cases that I think are not.

**Situation where it's useful:**

* The "RSGF review windows": let's say I am reviewing a game, and I remember a similar sequence from a previous game, I appreciate to be able to re-open the other RSGF file to compare.
* The "open position" windows (from the "RSGF review windows"): let's say that during a review, I want to compare the result of an invasion at move 52 and the same invasion but at move 71 to see what would be the best timing for that invasion, then I will open two windows, play the sequence out in both windows and compare. Note that each windows launch its own set of GTP bots, they are not sharing anything (which result in higher memory consumption).

**Situation where it's useless:**

* the Setting panel
* the graph windows, if more that one are opened from the same RSGF review windows

Practically, the difficulty with managing all those windows is to remember the relationships "parent/child" between windows, so that closing a windows trigger the closing of all its child windows. So far it's working well.

But one issue I have is with "bringing in focus" an existing windows. You can check **OpenChart.goto_move()** method in dualview.py (https://github.com/pnprog/goreviewpartner/blob/master/dual_view.py) to check what I did try already.

**Comment by pnprog** [comment]
> But one issue I have is with "bringing in focus" an existing windows.

Oh, I just found out why it would not work and fixed that :)
