### ISSUE TITLE
Problem to work with latest AQ 2.1.1

### ISSUE THREAD

**Issue by liverex** [pnprog/goreviewpartner#15]
When I began to use the latest AQ 2.1.1, I got this error:

......
now asking AQ to play the game move: black at d4
leaving consume_stderr thread
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\tools\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "c:\tools\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\sgf\goreviewpartner-master\toolbox.py", line 655, in run_all_analysis
    self.run_analysis(self.current_move)
  File "c:\sgf\goreviewpartner-master\aq_analysis.py", line 184, in run_analysis
    aq.place_black(ij2gtp(player_move))
  File "c:\sgf\goreviewpartner-master\gtp.py", line 92, in place_black
    if answer[0]=="=":return True
IndexError: string index out of range

Traceback (most recent call last):
  File "c:\sgf\goreviewpartner-master\aq_analysis.py", line 425, in <module>
    top.mainloop()
  File "c:\tools\Python27\lib\lib-tk\Tkinter.py", line 1017, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
Terminate batch job (Y/N)? y

**Comment by pnprog** [comment]
Hi!

I downloaded AQ 2.1.1 and was able to reproduce the issue: Apparently, the new version of AQ is not able to undo a move anymore, it is like a regression because previous version could.

Now, Rayon, the other bot, also cannot undo a move, and so I have a workaround ready for this situation, I will try it on AQ.

It should work, but otherwise, I will open an issue on AQ project.

**Comment by liverex** [comment]
Thanks a lot. @pnprog

**Comment by pnprog** [comment]
I tryed that workaround of AQ 2.1.1 and it works.

Code has been pushed to github, you can try now, or wait for the "windows" release I plan for this week (version 0.10).

**Comment by liverex** [comment]
It works. Thank you very much.

**Comment by jfsamper** [comment]
Hi, I'm still having the same problem with the latest grp. I don't know why the workaround isn't working for me, maybe because I'm using AQ-mini (cpu only)?

thanks

**Comment by pnprog** [comment]
I am using AQ-mini cpu as well, so I don't think this is linked with that.

In fact, the workaround is "pure GTP": instead of sending the undo command, I send a **clearboard** command followed by plenty of **play black xx** and **play white xx** commands for all moves of the game.

Can you provide more information, like the failure message in the "terminal looking windows"?
