### ISSUE TITLE
A bug in init translation dictionary

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#53]
if line[:len(key)+2]==key+' "':
			entry=line[len(key)+2:-2]  #entry=line[len(key)+2:-1] is wrong
			translation=""

		key="msgstr"
		if line[:len(key)+2]==key+' "':
			translation=line[len(key)+2:-2]  #same  error

**Comment by pnprog** [comment]
Hi!

What are the consequence of this bug?

As I understand, `entry=line[len(key)+2:-2]` instead of `entry=line[len(key)+2:-1]` means the string in variable **entry** (as well as in **translation**) will be shortened by one more char from the right side. Like **This is GoReviewPartne** instead of **This is GoReviewPartner** (last letter missing), and **GoReviewPartner欢迎** instead of **GoReviewPartner欢迎您**

And so, on my system, the translations do not work anymore (for chinese, french, korean...).

**Comment by pnprog** [comment]
Could it be that you saved the **zh.po** file using **CRLF** for end of line character, instead of the usual **LF**? ( `\r\n` instead of `\n` ) this would add an extra character at each line (https://en.wikipedia.org/wiki/Newline).

If so, I can maybe find a work-around to work for both types.

**Comment by pnprog** [comment]
I just pushed that commit: https://github.com/pnprog/goreviewpartner/commit/02e934899bd7451b20f1d75f74b1daff70591051

The **.strip()** method should remove any extra newline character. Tell me if things are working better now.

**Comment by jiangwuyou** [comment]
Yeah. It will return an extra ":) You should have fixed that issue now:)
