### ISSUE TITLE
Could not save the RSGF file

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#55]
etting time per move
size of the tree: 19
Saving RSGF file 2018-05-09_22-56_浜篲vs_浜?rsgf????????????????????????????????
Could not save the RSGF file 2018-05-09_22-56_浜篲vs_浜?rsgf????????????????????????????????
'ascii' codec can't encode character u'\u4eba' in position 56: ordinal not in range(128)

You can use
Line 224:
		new_file=codecs.open(filename,"w","utf-8")
#		new_file=open(filename,'w')
Line 241:
		new_file=codecs.open(filename,"w","utf-8")
#		new_file=open(filename,'w')

**Comment by pnprog** [comment]
Hi!

I patched it to try first `new_file=open(filename,'w')` then `new_file=codecs.open(filename,"w","utf-8")` it the first one failed. Because on my system, the first method works, but not the second method.

This makes me a bit uncomfortable, because it shows there is clearly something I don't understand here :(

Could you share the file the **2018-05-09_22-56_浜篲vs_浜.sgf** ? I would like to investigate with this file to see how it would work on my system.

**Comment by jiangwuyou** [comment]
>Could you share the file the 2018-05-09_22-56_浜篲vs_浜.sgf ? I would like to investigate with this file to see how it would work on my system.
Needn't to share because that file is produced by GRP for Run a live analysis menu on Chinese GUI, since the robot has a Chinese name.

**Comment by jiangwuyou** [comment]
I close that thread. "'ascii' codec can't encode character"  issue happened frequently in many code line for the older package. Now I meet fe simlar issue in the latest package:)

**Comment by pnprog** [comment]
Not so fast, I catch another bug in link with UTF-8 translation: https://github.com/pnprog/goreviewpartner/commit/86e8126edd4ce4be8b7332d30b15d2e7e7cc9d63

Next week, I will have access to a Chinese computer with windows 7, so I will be to test all this thoroughly.

**Comment by jiangwuyou** [comment]
What's your development environment and utility for GRP? My test tools are Visual Studio 2017+Python2.7+PyInstaller.

**Comment by pnprog** [comment]
I run Python 2.7.14 under Linux/Ubuntu, I ran GRP directly from the command line (ie: **python2 main.py**)

**Comment by fishcu** [comment]
I, too, have had major pain with unicode and decoding/encoding in the past. This video helped me a lot in understanding the problems I was facing: https://www.youtube.com/watch?v=sgHbC6udIqc

Highly recommended!

**Comment by pnprog** [comment]
Hi @fishcu ,
> I, too, have had major pain with unicode and decoding/encoding in the past. This video helped me a lot in understanding the problems I was facing: https://www.youtube.com/watch?v=sgHbC6udIqc

That video was really interesting! I had never quite see the difference between "Unicode" and "utf-8" (the first one beeing an object type, the second an encoding format for the former). I decided to follow the advise of the video to convert every input into Unicode object, and deal only with Unicode in GRP code, then convert back to string object for GRP output.

I started by making a survey of all GRP's input/output:

![image](https://user-images.githubusercontent.com/25114663/40777286-0df0c3e4-6500-11e8-9dc5-723098b7f96a.png)

Then I worked my way to make those conversion back and forth to Unicode for all of them (Gomill was the complicated one). Also, I added **from __future__ import unicode_literals** at the top of each python files, so that a declared string automatically becomes an Unicode one.

All of this makes for a pretty big commit: https://github.com/pnprog/goreviewpartner/commit/2eb4ff3a5a3a40a5489faa333fe21fae0b7d1104

But I guess it is pretty good now. Although, I think I really understand all this mess about encoding :)
It's complicated, but it's because Python does not let us mess with it, and is very strict about this, in the end, it's a good thing for a program like GTP.

**Comment by fishcu** [comment]
Congrats! I am sure you learned a lot. Did it also fix some of the issues related to text encoding?

**Comment by jiangwuyou** [comment]
>All of this makes for a pretty big commit: 2eb4ff3
I'm planing to download and recompile it to see whether there's no new issue on July 3rd.

**Comment by pnprog** [comment]
Haha, it turned out I had also forgotten the encoding issue with the bots command line parameters encoding :)

I got my hand on a computer with an Chinese installation of Windows, very useful to find issue that I could not produce on my computer.

For the record:
![image](https://user-images.githubusercontent.com/25114663/40793967-7550bf96-6530-11e8-9c0d-35677af9e2cc.png)

**Comment by jiangwuyou** [comment]
>it turned out I had also forgotten the encoding issue with the bots command line parameters encoding :)
> got my hand on a computer with an Chinese installation of Windows, very useful to find issue that I could not produce on my computer.

Yeah. I found a decode bug for parsing  GTP in the older code on Chinese Windows XP. So after you commit fully your modification, I will test it.
