### ISSUE TITLE
SOS: Continue SGF file analysis feature requirement

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#65]
Issue:
Notebook has to suspend OS for overburn when I run SGF file analysis. Then I will get a RSGF file, which can be used partly. I wish
When click Run a SGF file analysis, GRP will check the existence of old RSGF file, and load it to continue the SGF analysis.

Please complement that useful feature ASAP:)

If you haven't time to do it, I will complement that feature after you release the major committed version for encode/decode string.

**Comment by pnprog** [comment]
Hi!

I just implemented the feature. So now, when you run an analysis, you can select the RSGF file instead of the SGF file:

![image](https://user-images.githubusercontent.com/25114663/40842094-4eafdbec-65df-11e8-94bf-dd8ea2731699.png)

Then, GRP will notice it's an already analyzed file, so it will ask you what to do with the existing variations:

![image](https://user-images.githubusercontent.com/25114663/40842141-70ee8dc0-65df-11e8-90b5-67a83a0ff6e0.png)

You can choose "keep": the moves with existing variations are not analyzed again, so the analyze is skipped for those moves, but the variations and data stay in the RSGF file. This is what to use when resuming an analysis after you reboot your computer.

You can also choose "replace" then the former variations/data will be discarded and replaced by new ones. This is useful for this use case: You can first analyze a game with a fast profile to see the win rate graph and get an idea where you wen't wrong. Then you can rerun the analyze on a limited range of moves (for example only middle game, or the area where the win rate dropped a lot) using the slow profile to have a deeper analysis on those moves. After that, the RSGF contains analysis for all moves, but detailed analysis only on the limited range for the second analysis run.

You could also run the fast analysis on your opponent's moves, and the slow analysis on your moves only? Should be ok, I did not tried yet.

Note: When analyzing a RSGF file, GRP automatically select the SGF first line of play (first variation).

**Comment by pnprog** [comment]
By the way, the encode/decode commit is done and tested, please have a try and let me know :)

**Comment by jiangwuyou** [comment]
Good news:)
Thanks very much:)
