### ISSUE TITLE
UnicodeDecodeError for str(e)

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#67]
For instance,
show_error(_("Could not run the program:")+"\n"+str(e),self.parent)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 15: ordinal
 not in range(128)

Maybe you can use
reload(sys) 
sys.setdefaultencoding('utf-8')

Because

STDOUT encoding: cp936
STDERR encoding: cp936

**Comment by pnprog** [comment]
Hi!

Thanks a lot, your help is very valuable to me!

Regarding this issue, I overlooked that IOError (and probably most Exceptions) return str message (not unicode) and so it has to be dealt with as well. I replace those **str(e)** by **unicode(e)** (maybe not the best solution) and created a dedicated Exception class to deal with specific unicode error messages: https://github.com/pnprog/goreviewpartner/commit/b5a894081db11217eb53ec133c4d6416b45a39e5

Could you have a try again?

Regarding the possibility to use:
```
reload(sys)
sys.setdefaultencoding('utf-8')
```
I read everywhere that this solution is dangerous, because it change also the behaviour of the imported modules. So they may not work as expected.

I choose to use **from __future__ import unicode_literals** instead, because it only affect my own modules, so it's easier for me to keep everything under control.

Thanks again for your help, it is very useful to me.

**Comment by jiangwuyou** [comment]
I have translated the latest English content, and will upload a zh.po soon.

I have recompiled leela-zero, and your GRP is the only tool, which can run on Windows XP now:)

But maybe I have found a "list index out of range" since it happed twice on Windos XP. I will recur in on Win 10 and fix it after I clone your latest package.

**Comment by jiangwuyou** [comment]
Here is <a href=http://www.hxtt.com/zh.po>http://www.hxtt.com/zh.po</a>

**Comment by pnprog** [comment]
This is pretty cool :)
I think I will install an instance of Windows XP in virtualbox this week to have a try as well!

I am curious: will you run GRP in Windows XP only inside virtual box? or do you really have some Windows XP computers that you need to run GRP on?

Regarding the translation, is it OK for you if I give you write access to this Github project? this way, you can directly update the ZH translation without me having to approve. Ok for you?

**Comment by pnprog** [comment]
Hi!

I have give you write access to this project, so you can now directly modify the **zh.po** file at your own pace. Thanks for your help in making GRP a better software :)

I will soon have a try with windows XP in virtualbox, but I will probably stick with **gnugo** instead of LeelaZero, to help differentiate issues due to LeelaZero and issues dues to GRP. If my GRP+gnugo has issues, then it's most certainly and issue with GRP.
