### ISSUE TITLE
A strange thread issue only on XP

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#68]
move 196
leela Zero play white
leaving consume_stderr thread
converting GRPException error message from unicode to str
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "toolbox.py", line 1012, in run_all_analysis
  File "leela_zero_analysis.py", line 34, in run_analysis
  File "gtp.py", line 149, in play_white
GRPException: GRPException in genmove_white()
answer=''
list index out of range

move 182
leela Zero play white
leaving consume_stderr thread
Met Win XP bug:(
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "toolbox.py", line 1012, in run_all_analysis
  File "leela_zero_analysis.py", line 34, in run_analysis
  File "gtp.py", line 144, in play_white

So I add a flag in gtp.py :
		self.flag4thinking=False

def consume_stderr(self):
		while 1:
			try:

				if self.flag4thinking:
					sleep(.1)
					continue

				err_line=self.process.stderr.readline()

def play_black(self):

		self.flag4thinking=True

		self.write("genmove black")
		answer=self.readline().strip()

		self.flag4thinking=False

	def play_white(self):

		self.flag4thinking=True

		self.write("genmove white")
		answer=self.readline().strip()

		self.flag4thinking=False
	
Then happen:
move 231
leela Zero play black
converting GRPException error message from unicode to strleaving consume_stderr
thread
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "toolbox.py", line 1012, in run_all_analysis
  File "leela_zero_analysis.py", line 37, in run_analysis
  File "gtp.py", line 129, in play_black
GRPException: GRPException in genmove_black()
answer=''
list index out of range

So my conclusion is
For XP,
Sometimes other PY threads will result the empty answer:(

Can you provide a feature:
When catch "list index out of range" exception, restart leelaz to continue Analysis?

The solo GoreviewPartner/leelaZero package for Windows XP is at <a href=http://www.hxtt.com/GoReviewLeelaELF.zip>GoReviewLeelaELF.zip (143MB)</a>, which contains the latest Leela weights and ELF weights.

**Comment by pnprog** [comment]
Whoa, I am impressed LeelaZero can be ran on Window XP!

Those two errors:
```
GRPException: GRPException in genmove_white()
answer=''
```
and
```
GRPException: GRPException in genmove_black()
answer=''
```
They mean that the **leelaz.exe** crashed or failed and terminated, so GRP get an empty answer to the GTP command **genmove black/white**.

To provide more details:

1. First, GRP asks **leelaz.exe** for a move (using **genmove black/white**), and is stuck waiting until it gets an answer from **leelaz.exe** through GTP. So **answer=self.readline().strip()** is blocking.
2. In parallel, there is that **consume_stderr** thread that reads any output on **stderr** and put it into that queue **self.stderr_queue.put** for GRP to read when it is ready. Reading from **stderr** is blocking for the process as well (thread is blocked at **err_line=self.process.stderr.readline()**)
3. Then, **only after** GRP gets an answer from **leelaz.exe** about what move to play as black or white, GRP will start to read the **stderr** messages in the queue. That means, GRP is sure that LeelaZero is not thinking anymore, because GRP got LZ's answer and that particular move. I still add some buffer time (those **sleep(.1)**) to be sure the information had enough time to be transferred from **stderr** to the queue, but normally, it will all be printed to **stderr** by LZ before LZ's answer is printed to **stdout** for GRP to read, so it should be fine.

Anyway, reading an empty string on **stderr** or **stdout** means the process crashed, and it terminated.

I could certainly try to catch that **answer=''**, and restart **leelaz.exe**, but it does not look like a good solution: I am afraid to get other users into an infinite restart/crash loop, that will make them loose control of their computers. Also, if for some reason, one user needs to kill the thread, then having it restarted right away will not make it happy :)

At least, I need to add a setting that the user needs to apply to allow automatic restart, this way it is safer :)

On your side, do you have any idea why this is happening? Maybe your computer runs out of RAM, so Windows kills the process?

Maybe it's getting too hot and become unstable? (an other user had that issue). You can try to add some sleep time (to let him cool down) in **toolbox.py** around line 1016, as follow (add **time.sleep(10)**):

```
	def run_all_analysis(self):
		self.current_move=1

		while self.current_move<=self.max_move:
			answer=""
			if self.current_move in self.move_range:
				parent=go_to_move(self.move_zero,self.current_move-1)
				if len(parent)>1:
					log("Removing existing",len(parent)-1,"variations")
					for other_leaf in parent[1:]:
						other_leaf.delete()
				answer=self.run_analysis(self.current_move)
				time.sleep(10)
				self.total_done+=1
				write_rsgf(self.rsgf_filename,self.g)
				log("For this position,",self.bot.bot_name,"would play:",answer)
				log("Analysis for this move is completed")
```

Does this happen all the time? If not so frequent, it is possible to simply resume the analysis?

**Comment by jiangwuyou** [comment]
>Whoa, I am impressed LeelaZero can be ran on Window XP!
Yeah. I have succeeded in analysising three RGF/SGF files for test:) I recompile it and searched a OpenCL.dll for XP, then test/debug to make sure it can run:)

>but it does not look like a good solution: I am afraid to get other users into an infinite restart/crash loop, 
Don't worry. Sometimes it can parse more than 150 moves, and sometimes it parses only 10 moves. I doubt my test PC is too old, and I will try to find why. Anyway, a counter for restart total number or frequnce, is useful:)

**Comment by jiangwuyou** [comment]
Tested . Need XP SP3 and msvc140.dll .
When I close Sleep mode (display/harddisk), the GRP in XP Sp3 on a Virtualbox have succeeded in analysising a SGF file:)

I will test more.

**Comment by jiangwuyou** [comment]
For Win XP, Display entering sleep mode is the key, although it's running on CPU mode:) 

Test seems OK until now:)

**Comment by l1t1** [comment]
@jiangwuyou i download you zip file, and run it on windows 2003, it reports some dll missing
i download msvcp140.dll and vcruntime140 and copy them to leela directory, and their error are fixed.
but the api-ms-win-crt-runtime-l1-1-0.dll error cannot be fiexed by same way. could you aslo attach the file of your system?

**Comment by l1t1** [comment]
I run leelaz -w elf.txt --benchmark on win2003r2 32bit E78870 4GB ram
and it exit after print
```
Playouts: 144, Win: 51.22%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B1
6 D15 D17 B15 E17 F16 C10 O17 M17
```
same command on win7 64bit i5 6600 8GB ram
```
Playouts: 2690, Win: 50.82%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B
16 D15 D17 B15 E17 F16 C10 O17 M17 R3 R4 Q3 O3 P3
Playouts: 2699, Win: 50.82%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B
16 D15 D17 B15 E17 F16 C10 O17 M17 R3 R4 Q3 O3 P3
```
and sames will not stop

**Comment by l1t1** [comment]
strange, I rerun it on win2003r2 exit after print
```
Playouts: 593, Win: 50.98%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B1
6 D15 D17 B15 E17 F16 C10 R3 R4 Q3
```

**Comment by l1t1** [comment]
```
gogui-twogtp.exe -black "leelaz.exe -g -w 5b59.gz -v3201 --noponder -m4 -t1 -s1" -white "leelaz.exe -g -w  elf.txt -v3201 --noponder -m4 -t1 -s1" -auto -sgffile 5b59_elf -kom
i 7.5 -games 1000
```
exit after first game finished

**Comment by l1t1** [comment]
the computer is a vmware virtual machine, so it seems not too hot, i will try your method tomorrow

**Comment by jiangwuyou** [comment]
>Visual C++ 2015 Redistributable (x86) package

Yeah. I haven't tested it on Win 2003, but I can make sure Visual C++ 2015 Redistributable (x86) package(vc_redist.x86.exe ) contains some  basic dll files.

**Comment by jiangwuyou** [comment]
I wrote an OpenCL test program, and found my old Pentinum T3400 doesn't support OpenCL. So I can only test leelaz.exe for Win XP.
Other test pc will throw exception, but my Win XP for T3400  will shutdown without prompt in a few moves:)  So that the overheating issue should be the answer, because my old notebook with T3400 has that issue.

**Comment by jiangwuyou** [comment]
I spent one hour to clear dirty of cool fan for T3400 CPU. It analysised 47 moves, then throw an exception:) So the key for Win XP is CPU overheting.
