### ISSUE TITLE
Running grp on macOS

### ISSUE THREAD

**Issue by Dreamkeeper66666** [pnprog/goreviewpartner#69]
I just downloaded the source code and ran the main.py and got the following results. Anybody knows what's gone wrong? Thanks a lot!
![screen shot 2018-06-04 at 12 24 12 pm](https://user-images.githubusercontent.com/35905034/40898192-792d1b5e-67f2-11e8-8f58-8f3e0357ef27.png)

**Comment by pnprog** [comment]
Very strange, python is not capable to detect the local used on your computer. This seems to be more a python issue.

Anyway, I will patch it in the next version, so that English is selected in case of such error.

As a temporary workaround:

1. Open the **config.ini** file
2. In the **[General]** section, set the **language** property as **en**

It will look like this:

```
[General]
language = en
sgffolder = 
rsgffolder = 
pngfolder = 
livefolder = 
```

**Comment by pnprog** [comment]
I patched GRP, so that it falls back to English in case the system language cannot be detected: https://github.com/pnprog/goreviewpartner/commit/4654ea573dd332d248628e44afb447390fa53ae7

**Comment by Dreamkeeper66666** [comment]
@pnprog Thanks a lot, it works now!
