### ISSUE TITLE
"Variations better than actual game move in blue" only colors the variations black

### ISSUE THREAD

**Issue by anonymousAwesome** [pnprog/goreviewpartner#75]
I created a rsgf analysis file with Leela Zero, version 0.15.  When it comes time to review the rsgf file, the display option "variations better than actual game move in blue" doesn't color any of the variations.  They're all black.  The other two options work as described.  

I poked around the source code a bit and I managed to trace the problem as far back as dual_view.py, specifically lines 1957-1972 and 1984-1999.  Unfortunately I'm not familiar with the node code you've used, so that's as far as I got.

**Comment by pnprog** [comment]
Hi! Thanks for reporting this, I will investigate the issue.

**Comment by anonymousAwesome** [comment]
Also, I had LZ only review the white moves.  I don't know if this is relevant or not.

**Comment by anonymousAwesome** [comment]
Okay, I just checked.  It works fine when I tell GRP to analyze both sides of the game.

**Comment by pnprog** [comment]
Hi @anonymousAwesome ,

In fact this is normal: in order to get the winning percentage of the actual game move, GRP uses the inverse winning rate of the following move. It proceeds this way, because the actual game move is not necessarily part of the bot proposed moves, and so win rate won't be available.

Moreover, the bot proposed moves often come with low playout, so are not that reliable.

Anyway, there is room for improvement here: Maybe I can tell GRP to record the win rate of the move if it is part of the bot proposed moves, and then, during analysis of the previous move, erase that value by using the newer better value.

**Comment by anonymousAwesome** [comment]
Mostly, I'd recommend just greying out that option or even removing it if only one side has been analyzed.
