### ISSUE TITLE
How can I save an RSGF after GRP reviewed my game?

### ISSUE THREAD

**Issue by someone235** [pnprog/goreviewpartner#87]
Is it saved somewhere by default? Or is there a way to save it manually?
Thanks in advance

**Comment by apetresc** [comment]
By default it's saved in the same place as the source SGF you were reviewing with it. It should save immediately once analysis is done.

**Comment by someone235** [comment]
Nevermind. I see it saves it

**Comment by pnprog** [comment]
@someone235 ,

Yes @apetresc is right: same place, same name except for the extension. The file is saved after each move analysis is done, so that in case of interruption, [the analysis can be resumed](http://yuntingdian.com/goreviewpartner/grp-documentation/doc.htm#resuming-an-analysis).

If you need it, I can add an option to specify where the file should be saved?

**Comment by someone235** [comment]
I don't really need it, but it wasn't intuitive for me at first.
