### ISSUE TITLE
Bug? Number of playouts for the move actually played

### ISSUE THREAD

**Issue by ashinpan** [pnprog/goreviewpartner#95]
I am not sure whether what I would like to request for is a bug-fix or feature. Anyhow, I would demonstrate with an example.

I used GRP to analyze the move 22, made by AG, in the AG vs. Ke Jie 1st game. The network used is the latest 196, with 80k playouts. After taking a long time (probably because my GPU is a lousy 1050), the following analysis is given: 

> Move 22
> White to play. In the game, white played E14
> For this position, Leela Zero would play: F17

> White Value Network win probability:
 > • before e14: 53.95%
 > • after e14: 63.61% (+9.66pp)

The number of playouts used to estimate LZ's favorite F17 is 61596, but that to evaluate AG's choice E14 is 1285 only. 

In this case, given that the actual move gives a much higher win probability, don't you think GRP (or lZ) should have given many more playouts for E14 variation to evaluate the actual move, instead for F17, which was not actually played?

**Comment by pnprog** [comment]
Hi!

> In this case, given that the actual move gives a much higher win probability, don't you think GRP (or lZ) should have given many more playouts for E14 variation to evaluate the actual move, instead for F17, which was not actually played?

Yes, I agree that quite often, LZ _over evaluates_ some positions, and does not explore enough other moves that seem promising.

But this is a behaviour of LZ, not something GRP can change.

Why this behaviour? I am not sure.
The self learning process aims at selecting the strongest playing network, and how to select what move to evaluate, what move to not evaluate, and what move to pick is what makes one network stronger or weaker.

_Maybe_, if more thinking power was allocate to evaluate **e14** in your example above, the win rate would start to quickly drop and end below the win rate of **f17**. _Maybe_ the network has learned to avoid _wasting_ to much time on such moves?

**Comment by ashinpan** [comment]
@pnprog  Thanks. I would try to ask at LZ for a feature---the option to force explore a move.

**Comment by pnprog** [comment]
This is a way, yes: You can add a specific move as a variation in the SGF file, then, when selecting the file for analysis, you can tell GRP to analysis the second variation of the SGF file:
![image](https://user-images.githubusercontent.com/25114663/50557628-f959bb00-0d21-11e9-98c0-abab50cedb3a.png)
You can also rename the RSGF file into SGF, and reopen this file with GRP.

But if you only need to analyse one of the moved played during the game, then I am not sure if it is necessary: During the analysis, when the program is analysing move 23 (the answer played by KeJie) the probability of the best move find by GRP for KeJie is used to calculate "_retrospectively_" the win probability of AlphaGo move at 22:

In your example, I guess that after move 22 played by AlphaGo, GRP/LZ estimates that the best answer for KeJie has a 36.69% win rate, and so calculates the win rate of AlphaGo's move e14 at 100% - 36.69% = 63.61%

Quite often, the "first impression" of Leela Zero is not very accurate (because low number play-out) so using the next move to calculate the win-rate probability ensures that the 80k play-outs will be used to give a good estimation. (for this to work properly, move 22 **and** move 23 both need to be part of the range of moves to be analysed)

GRP is designed for batch analysis, so if you want to analyse some very specific moves or variation, you may use Lizzie (https://github.com/featurecat/lizzie) instead, which is better suited for this case I think.

**Comment by ashinpan** [comment]
Only now I have come to understand better how GRP works. Thanks for your patient explanation. I am closing this issue.

**Comment by pnprog** [comment]
You are welcome.
